/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mb.solrj;

import java.awt.Color;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.solr.client.solrj.SolrClient;
import org.apache.solr.client.solrj.SolrQuery;
import org.apache.solr.client.solrj.SolrQuery.ORDER;
import org.apache.solr.client.solrj.SolrServerException;
import org.apache.solr.client.solrj.impl.HttpSolrClient;
import org.apache.solr.client.solrj.response.QueryResponse;
import org.apache.solr.common.SolrDocument;
import org.apache.solr.common.SolrDocumentList;

/**
 *
 * @author Manuel
 */
public class jfrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jfrmPrincipal
     */
    public jfrmPrincipal(org.apache.solr.client.solrj.SolrQuery solrQuery) {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtColeccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtSearchString = new javax.swing.JTextField();
        jbtnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxaResults = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Colección:");

        jtxtColeccion.setText("CISI");

        jLabel2.setText("Cadena a buscar:");

        jtxtSearchString.setText("WhAt iS iNfOrM'aTiOn rE:tRiEvAl?!!");

        jbtnBuscar.setText("Buscar");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        jtxaResults.setColumns(20);
        jtxaResults.setRows(5);
        jScrollPane2.setViewportView(jtxaResults);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtxtColeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jbtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jtxtSearchString, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 187, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jtxtColeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtSearchString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed

        final String SOLR_CORE_URL = "http://localhost:8983/solr/" + jtxtColeccion.getText();
        final SolrClient solrClient = getSolrClient(SOLR_CORE_URL);
        SolrQuery solrQuery = new SolrQuery("*:*");
        //solrQuery.addField("id");
        //solrQuery.addField("title");
        //solrQuery.addField("author");
        String query;
        query = jtxtSearchString.getText();
        query = query.replaceAll("[\\+\\-\\&&\\!\\(\\)\\{\\}\\[\\]\\^\"\\~\\*\\?\\:\\/\\'\\.\\,\\:\\;]", "");
        query = query.toLowerCase();
        query = query.replaceAll("\\s", "||");
        query = "text:" + query;
        System.out.println("Consulta:\n" + query);
        solrQuery.setQuery(query);
        //solrQuery.setSort("id", ORDER.asc);
        solrQuery.setRows(25);
        solrQuery.setFields("ndoc", "score");
        // sends search request and gets the response
        QueryResponse response = null;
        jtxaResults.setText(null);
        try {
            response = solrClient.query(solrQuery);
        } catch (SolrServerException | IOException e) {
            System.err.printf("Failed to search articles: %s", e.getMessage() + "\n");
            jtxaResults.append("Failed to search articles: " + e.getMessage() + "\n");
        }
        // converts to domain objects and prints to standard output
        if (response != null) {
            SolrDocumentList articles = response.getResults();
            jtxaResults.setEditable(false);
            jtxaResults.append("Consulta:\n" + query + "\n");
            int res = 1;
            String result;
            for (SolrDocument article : articles) {
                result = String.format("%2s", res).replaceAll("\\s", "0");
                System.out.println(result + ": " + article.toString());
                jtxaResults.append(result + ": " + article.toString() + "\n");
                res++;
            }
        }
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private static SolrClient getSolrClient(String core_url) {
        return new HttpSolrClient.Builder(core_url).withConnectionTimeout(5000).withSocketTimeout(3000).build();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        jfrmPrincipal f = new jfrmPrincipal(null);
        f.setTitle("Buscador Solrj");
        f.setLocation(400, 150);
        f.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JTextArea jtxaResults;
    private javax.swing.JTextField jtxtColeccion;
    private javax.swing.JTextField jtxtSearchString;
    // End of variables declaration//GEN-END:variables
}
